version: "2.1"
services:
  duplicati:
    image: lscr.io/linuxserver/duplicati
    container_name: duplicati
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/London
      - CLI_ARGS= #optional
    volumes:
      - /docker/duplicati/config:/config
      - /docker/duplicati/backups:/backups
      - /media/External:/source
    ports:
      - 8200:8200
    restart: unless-stopped
